install:
  - npm install -g mocha
  - npm install
  - npm link

build: off

test_script:
  - mocha --require chai --reporter mocha-appveyor-reporter test/tests/mixed.js

cache:
  - node_modules -> package.json
